# Generated by Django 2.1.7 on 2019-04-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='probability',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
