# Generated by Django 2.1.7 on 2019-04-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0002_job_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job',
            field=models.CharField(max_length=150),
        ),
    ]
