# Generated by Django 2.1.7 on 2019-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0003_auto_20190406_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.FloatField(max_length=100)),
                ('link', models.CharField(max_length=150, null=True)),
                ('title', models.CharField(max_length=150, null=True)),
                ('content', models.CharField(max_length=300, null=True)),
                ('img', models.CharField(max_length=300, null=True)),
            ],
        ),
    ]
