# Generated by Django 2.1.7 on 2019-04-07 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0005_auto_20190407_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendation',
            name='content',
            field=models.CharField(max_length=20000, null=True),
        ),
    ]
