# Generated by Django 2.1.7 on 2019-04-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0006_auto_20190407_0453'),
    ]

    operations = [
        migrations.AddField(
            model_name='recomendation',
            name='job',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
