# Generated by Django 2.1.7 on 2019-04-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobber', '0007_recomendation_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recomendation',
            name='img',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='job',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='link',
            field=models.CharField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='type',
            field=models.CharField(max_length=1000),
        ),
    ]
